version: "3.4"

services:
  one-hub:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: done-hub  <-- 删除，防止冲突
    networks:
      - dokploy-network
    restart: always
    # ports:
    #   - "3066:3000"  <-- 删除，Dokploy 不需要映射宿主机端口
    volumes:
      - ./data:/data
    environment:
      - SQL_DSN=oneapi:123456@tcp(db:3306)/done-hub
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string  # 建议改为复杂的随机字符串
      - USER_TOKEN_SECRET=random_string # 建议改为复杂的随机字符串
      - TZ=Asia/Shanghai
    depends_on:
      - redis
      - db
    # -------------------------------------------------
    # 删除了 healthcheck，因为你的容器里可能没有 wget 命令
    # 导致误判为 unhealthy，从而导致域名无法访问
    # -------------------------------------------------

  redis:
    image: redis:latest
    # container_name: redis
    restart: always
    networks:
      - dokploy-network

  db:
    image: mysql:8.2.0
    restart: always
    # container_name: mysql
    networks:
      - dokploy-network
    volumes:
      - ./data/mysql:/var/lib/mysql
    # ports:
    #   - "3306:3306" <-- 删除，保护数据库不被外网扫描
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "DoneHub@justsong"
      MYSQL_USER: oneapi
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: done-hub

networks:
  dokploy-network:
    external: true
